"""сделал ait_type как строку в AI_MODEL

Revision ID: 27f55cc6199b
Revises: 2892098274f0
Create Date: 2025-12-07 17:23:27.092955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f55cc6199b'
down_revision: Union[str, Sequence[str], None] = '2892098274f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ТОЛЬКО добавляем новый столбец, не трогаем ai_type!
    op.add_column('ai_models', 
        sa.Column('aimodel_type', sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ТОЛЬКО удаляем новый столбец
    op.drop_column('ai_models', 'aimodel_type')
    # ### end Alembic commands ###