"""удалил ненужную связть AI_MODEL с AI_type

Revision ID: 5ca7188f190a
Revises: 27f55cc6199b
Create Date: 2025-12-07 17:35:34.897491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca7188f190a'
down_revision: Union[str, Sequence[str], None] = '27f55cc6199b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_models_ai_type_fkey'), 'ai_models', type_='foreignkey')
    op.drop_column('ai_models', 'ai_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('ai_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('ai_models_ai_type_fkey'), 'ai_models', 'ai_types', ['ai_type'], ['id'])
    # ### end Alembic commands ###
