"""added price column for AI_Model

Revision ID: 8630645f467d
Revises: c979c3263d9b
Create Date: 2025-12-02 00:00:43.080613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8630645f467d'
down_revision: Union[str, Sequence[str], None] = 'c979c3263d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('price', sa.String(length=20), nullable=True, default='0.1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_models', 'price')
    # ### end Alembic commands ###
